### PR TITLE
Update to latest version.

### PR DESCRIPTION
**Pull request by andy840119**
Update to latest nuget package.

Seems it will cause some breaking errors : 
- `TimelineBlueprintContainer` not working in `singer` or `lyric maker` screen because it need `HitObjectComposer`.
  - Might create singer's own `HitObjectComposer`(e.g: `SingerHitObjectComposer`) and implement playfield, then in playfield to implement create drawable.
- `Lyric` shows very early in playing screen(Fixed).
- Cannot see result page now, and here's the error.
    > A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Cannot mutate the children of a Loaded CompositeDrawable while not on the update thread. Consider using Schedule to schedule the mutation operation.)
    - Oops It's caused in older version, #249 will handler it.

Also : 
- See `OsuPlayfield` because create drawable is moved into playfield.
- Check `DrawableHitObject` to see is there any change like adding or removing methods.

### CODE REVIEW

**Comment by andy840119** [comment]
乾
被改成不知道怎麼修的狀態了
機掰

**Comment by andy840119** [comment]
This update is weird 🤔 
Maybe wait for next update for stablize.

**Comment by andy840119** [comment]
https://github.com/LumpBloom7/hishigata/pull/17
maybe follow how here doing 🤔

**Comment by smoogipoo** [comment]
Is the weird part the editor?

Can you give me a quick explanation of your editor structure? Where everything is placed - specifically `LyricBlueprintContainer` and `LyricEditorScreen`?

**Comment by andy840119** [comment]
Editor structure is in #248.
.
Most broken is in gameplay part.
Need to make a screenshot after back home.
.
Also i'm not sure is [OsuPlayfield](https://github.com/ppy/osu/blob/master/osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs#L101) is final now or will have big change.
And any suggestion to replace from `CreateDrawableRepresentation` with `registerPool` in playfield now, or be later?

**Comment by smoogipoo** [comment]
I'd suggest using pooling later after we have appropriate documentation for it. `OsuPlayfield` is final.

**Comment by andy840119** [comment]
Lyric shows too early has been fixed :P , happy/
.
@smoogipoo is there any big change in `2020.1031`'s version?
It crash on my ruleset while gameplay to result screen(in #249 ).
I'm not sure is there extra ways need to be implemented?

**Comment by LumpBloom7** [comment]
I can't really get any meaningful info of what is happening in the code due to being straight up unable to start the test project. Running the package in a release of lazer seems to at least get us to result screen no problem.
image

**Comment by LumpBloom7** [comment]
Here is the relevant logs that may clue one in on the general issues.
```
2020-11-17 15:15:28 [error]: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Cannot mutate the children of a Loaded CompositeDrawable while not on the update thread. Consider using Schedule to schedule the mutation operation.)
2020-11-17 15:15:28 [error]: ---> osu.Framework.Graphics.Containers.CompositeDrawable+InvalidThreadForChildMutationException: Cannot mutate the children of a Loaded CompositeDrawable while not on the update thread. Consider using Schedule to schedule the mutation operation.
2020-11-17 15:15:28 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.ensureChildMutationAllowed()
2020-11-17 15:15:28 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.ClearInternal(Boolean disposeChildren)
2020-11-17 15:15:28 [error]: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.LoadSamples()
2020-11-17 15:15:28 [error]: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.onSamplesChanged(Object sender, NotifyCollectionChangedEventArgs e)
2020-11-17 15:15:28 [error]: at osu.Framework.Bindables.BindableList`1.BindCollectionChanged(NotifyCollectionChangedEventHandler onChange, Boolean runOnceImmediately)
2020-11-17 15:15:28 [error]: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.Apply(HitObject hitObject, HitObjectLifetimeEntry lifetimeEntry)
2020-11-17 15:15:28 [error]: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.onDefaultsApplied(HitObject hitObject)
2020-11-17 15:15:28 [error]: at osu.Game.Rulesets.Objects.HitObject.ApplyDefaults(ControlPointInfo controlPointInfo, BeatmapDifficulty difficulty, CancellationToken cancellationToken)
2020-11-17 15:15:28 [error]: at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(RulesetInfo ruleset, IReadOnlyList`1 mods, Nullable`1 timeout)
2020-11-17 15:15:28 [error]: at osu.Game.Screens.Ranking.Statistics.StatisticsPanel.<>c__DisplayClass13_1.<populateStatistics>b__0()
2020-11-17 15:15:28 [error]: at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
2020-11-17 15:15:28 [error]: --- End of stack trace from previous location where exception was thrown ---
2020-11-17 15:15:28 [error]: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2020-11-17 15:15:28 [error]: --- End of inner exception stack trace ---
2020-11-17 15:15:28 [error]: An unobserved error has occurred. (inner)
2020-11-17 15:15:28 [error]: osu.Framework.Graphics.Containers.CompositeDrawable+InvalidThreadForChildMutationException: Cannot mutate the children of a Loaded CompositeDrawable while not on the update thread. Consider using Schedule to schedule the mutation operation.
2020-11-17 15:15:28 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.ensureChildMutationAllowed()
2020-11-17 15:15:28 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.ClearInternal(Boolean disposeChildren)
2020-11-17 15:15:28 [error]: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.LoadSamples()
2020-11-17 15:15:28 [error]: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.onSamplesChanged(Object sender, NotifyCollectionChangedEventArgs e)
2020-11-17 15:15:28 [error]: at osu.Framework.Bindables.BindableList`1.BindCollectionChanged(NotifyCollectionChangedEventHandler onChange, Boolean runOnceImmediately)
2020-11-17 15:15:28 [error]: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.Apply(HitObject hitObject, HitObjectLifetimeEntry lifetimeEntry)
2020-11-17 15:15:28 [error]: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.onDefaultsApplied(HitObject hitObject)
2020-11-17 15:15:28 [error]: at osu.Game.Rulesets.Objects.HitObject.ApplyDefaults(ControlPointInfo controlPointInfo, BeatmapDifficulty difficulty, CancellationToken cancellationToken)
2020-11-17 15:15:28 [error]: at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(RulesetInfo ruleset, IReadOnlyList`1 mods, Nullable`1 timeout)
2020-11-17 15:15:28 [error]: at osu.Game.Screens.Ranking.Statistics.StatisticsPanel.<>c__DisplayClass13_1.<populateStatistics>b__0()
2020-11-17 15:15:28 [error]: at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
2020-11-17 15:15:28 [error]: --- End of stack trace from previous location where exception was thrown ---
2020-11-17 15:15:28 [error]: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2020-11-17 15:16:29 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
2020-11-17 15:16:29 [error]: An unhandled error has occurred.
2020-11-17 15:16:29 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
2020-11-17 15:16:29 [error]: at osu.Game.Rulesets.Karaoke.Statistics.BeatmapMetadataGraph..ctor(IBeatmap beatmap)
2020-11-17 15:16:29 [error]: at osu.Game.Rulesets.Karaoke.KaraokeRuleset.CreateStatisticsForScore(ScoreInfo score, IBeatmap playableBeatmap)
```

**Comment by andy840119** [comment]
Guess need to run latest version with clean database 🤔

**Comment by LumpBloom7** [comment]
I think it's less database issues, but more async magic.

**Comment by LumpBloom7** [comment]
Given how convoluted everything is, there might even be several underlying causes.

**Comment by andy840119** [comment]
Hmm...
So sometimes it happen but sometimes not 🤔 ?

**Comment by andy840119** [comment]
Since crash at result screen is not caused in this release, i guess it's better to make a merge in this pr.
Remain : 
- Inject Composer and mark it as nullable.

**Pull request merged**
